apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: web
  ports:
    - port: 3000 # How other pods or objects inside the cluster access this.
      targetPort: 3000 # Port on the target pod we provide access to.
#     nodePort omit nodePort because this cluster ip is not accessible from the outside.
