apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: redis
  ports:
    - port: 6379 # How other pods or objects inside the cluster access this.
      targetPort: 6379 # Port on the target pod we provide access to.
#     nodePort omit nodePort because this cluster ip is not accessible from the outside.
