apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - port: 5000 # How other pods or objects inside the cluster access this.
      targetPort: 5000 # Port on the target pod we provide access to.
#     nodePort omit nodePort because this cluster ip is not accessible from the outside.
